services:
  app:
    build: .docker/app
    stdin_open: true
    tty: true
    container_name: app.taskproject
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "5173:5173"
    volumes:
      - ./:/task
    working_dir: /task/app
    user: 1000:1000

  api:
    build: .docker/api
    stdin_open: true
    tty: true
    container_name: api.taskproject
    environment:
      NODE_ENV: development
      COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "3003:3000"
      - "7878:7878"
    volumes:
      - ./:/task
    working_dir: /task/api
    user: 1000:1000

  mysql:
    build: .docker/mysql
    container_name: mysql.taskproject
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: task
      MYSQL_USER: task
      MYSQL_PASSWORD: task
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database:/database:rw
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: pma.taskproject
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql.taskproject
      PMA_USER: task
      PMA_PASSWORD: task
      UPLOAD_LIMIT: 250M
    restart: always

  android-builder:
    build:
      context: .docker/android-builder
      args:
        - BUILDPLATFORM=linux/amd64
    platform: linux/amd64
    container_name: android-builder.taskproject
    volumes:
      - ./app:/workspace
    profiles:
      - android

volumes:
  mysql_data:
    driver: local
